DISEASES_AND_CONDITIONS = {
    "diabetes",
    "type 1 diabetes",
    "type 2 diabetes",
    "prediabetes",
    "hypertension",
    "high blood pressure",
    "low blood pressure",
    "high cholesterol",
    "heart disease",
    "coronary artery disease",
    "heart attack",
    "stroke",
    "asthma",
    "copd",
    "pneumonia",
    "bronchitis",
    "tuberculosis",
    "flu",
    "influenza",
    "covid",
    "covid-19",
    "common cold",
    "cancer",
    "breast cancer",
    "lung cancer",
    "prostate cancer",
    "skin cancer",
    "arthritis",
    "osteoarthritis",
    "rheumatoid arthritis",
    "osteoporosis",
    "migraine",
    "epilepsy",
    "anemia",
    "thyroid disease",
    "hypothyroidism",
    "hyperthyroidism",
    "pcos",
    "endometriosis",
    "ibs",
    "gerd",
    "kidney disease",
    "liver disease",
    "fatty liver",
    "hepatitis",
    "ulcer",
    "gastritis",
    "obesity",
    "depression",
    "anxiety",
    "insomnia",
    "dementia",
    "alzheimer's disease",
    "parkinson's disease",
}


SYMPTOMS = {
    "fever",
    "cough",
    "headache",
    "migraine",
    "fatigue",
    "weakness",
    "dizziness",
    "nausea",
    "vomiting",
    "diarrhea",
    "constipation",
    "abdominal pain",
    "chest pain",
    "back pain",
    "joint pain",
    "muscle pain",
    "sore throat",
    "runny nose",
    "shortness of breath",
    "difficulty breathing",
    "rapid heartbeat",
    "palpitations",
    "swelling",
    "rash",
    "itching",
    "bleeding",
    "weight loss",
    "weight gain",
    "loss of appetite",
    "insomnia",
}


BODY_SYSTEMS = {
    "heart",
    "brain",
    "lungs",
    "kidneys",
    "liver",
    "stomach",
    "intestines",
    "pancreas",
    "thyroid",
    "skin",
    "bones",
    "muscles",
    "blood",
    "immune system",
    "nervous system",
    "digestive system",
    "respiratory system",
    "cardiovascular system",
}


HEALTH_AND_WELLNESS = {
    "nutrition",
    "healthy diet",
    "diet",
    "exercise",
    "physical activity",
    "sleep",
    "sleep health",
    "mental health",
    "stress",
    "stress management",
    "weight management",
    "hydration",
    "vaccination",
    "vaccines",
    "immunization",
    "first aid",
    "hygiene",
    "preventive care",
    "health screening",
    "sexual health",
    "maternal health",
    "child health",
    "elderly health",
}


MEDICAL_CONCEPTS = {
    "medication",
    "medicine",
    "drug",
    "treatment",
    "therapy",
    "side effects",
    "dosage",
    "surgery",
    "physical therapy",
    "chemotherapy",
    "radiation therapy",
    "immunotherapy",
    "diagnosis",
    "prevention",
    "symptoms",
    "causes",
    "risk factors",
}


HEALTH_TOPICS = (
    DISEASES_AND_CONDITIONS
    | SYMPTOMS
    | BODY_SYSTEMS
    | HEALTH_AND_WELLNESS
    | MEDICAL_CONCEPTS
)